# Generated by Django 6.0.6 on 2026-06-19 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('area_sqkm', models.FloatField()),
                ('ndvi', models.FloatField(blank=True, null=True)),
                ('ndbi', models.FloatField(blank=True, null=True)),
                ('mndwi', models.FloatField(blank=True, null=True)),
                ('geom_json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CapacityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_supply_capacity_liters_day', models.FloatField()),
                ('stp_capacity_liters_day', models.FloatField()),
                ('ward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='app.ward')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_liters_day', models.FloatField()),
                ('sewage_liters_day', models.FloatField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_usages', to='app.ward')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('ward', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ForecastTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_forecast_liters_day', models.FloatField()),
                ('sewage_forecast_liters_day', models.FloatField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_timeseries', to='app.ward')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('ward', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_years', models.IntegerField()),
                ('utility_type', models.CharField(max_length=10)),
                ('forecasted_demand_liters_day', models.FloatField()),
                ('stress_score', models.FloatField()),
                ('stress_tier', models.CharField(max_length=10)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_results', to='app.ward')),
            ],
            options={
                'unique_together': {('ward', 'horizon_years', 'utility_type')},
            },
        ),
    ]
